server: 
  contextPath: /t1
  port: 8090
      
info:
  app:
    encoding=@project.build.sourceEncoding@
    java.source=@java.version@
    java.target=@java.version@
    motd=JAMES Medici  Boot Actuator  
      

blogs: "controllersINFO"
endpoints: 
  shutdown: "enabledtrue"
facebook:
  client:
    accessTokenUri: "https://graph.facebook.com/oauth/access_token"
    authenticationScheme: query
    clientAuthenticationScheme: form
    clientId: 384261248599251
    clientSecret: fd7fa1c5f5a267f463263a0ce7ff2025
    tokenName: oauth_token
    userAuthorizationUri: "https://www.facebook.com/dialog/oauth"
  resource: 
    userInfoUri: "https://graph.facebook.com/me"
google: 
  client: 
    accessTokenUri: "https://accounts.google.com/o/oauth2/token"
    clientAuthenticationScheme: form
    clientId: 12894100090-tqso3lih5o42isneort886la2pesafmp.apps.googleusercontent.com
    clientSecret: 9xfU16efvxQ-BTMsXT9wOLpw
    scope: "profile email"
    userAuthorizationUri: "https://accounts.google.com/o/oauth2/auth"
  resource: 
    userInfoUri: "https://www.googleapis.com/oauth2/v3/userinfo"
guru: ~
linkedIn:
  client:
    accessTokenUri: "https://www.linkedin.com/oauth/v2/accessToken"
    clientId: 771mrzk94hye1w
    clientSecret: iIJFgBf9lCb18zYe
    userAuthorizationUri: "https://www.linkedin.com/oauth/v2/authorization"
  resource:
    userInfoUri: "https://api.linkedin.com/v1/people/~?format=json"
log4j: 
  logger:
    org: "thymeleafDEBUG"
logging:
  level:
    org: "hibernateERROR"
    springframework: "webINFO"
security:
  oauth2:
    resource:
      filter-order: 3
springframework: ~
twitter:
  client:
    accessTokenUri: "https://api.twitter.com/oauth/access_token"
    clientAuthenticationScheme: form
    clientId: oXJIDGVdB0PDnMICDwKckyzKm
    clientSecret: Z4BpN51kNsb2wbEfzDXm40v38W3I2P1u4H6fvfM6HQraVfry5j
    userAuthorizationUri: "https://api.twitter.com/oauth/authorize"
  resource:
    userInfoUri: "https://api.twitter.com/1.1/users/show.json"
